create extension if not exists pgcrypto;
create extension if not exists vector;

create type public.agent_status as enum ('active','paused','retired');
create type public.work_status as enum ('proposed','approved','running','blocked','completed','cancelled','failed');
create type public.risk_level as enum ('low','medium','high');

create table public.companies (id uuid primary key default gen_random_uuid(), name text not null, mission text not null default '', constitution jsonb not null default '[]', created_at timestamptz not null default now());
create table public.memberships (company_id uuid not null references public.companies on delete cascade, user_id uuid not null references auth.users on delete cascade, role text not null check(role in ('owner','executive','operator','auditor','viewer')), created_at timestamptz not null default now(), primary key(company_id,user_id));
create table public.departments (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, parent_id uuid references public.departments, name text not null, mandate text not null, status text not null default 'proposed', created_at timestamptz not null default now(), unique(company_id,name));
create table public.agents (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, department_id uuid references public.departments, name text not null, title text not null, mandate text not null, personality jsonb not null, authority text[] not null default '{}', model_policy jsonb not null default '{}', status public.agent_status not null default 'active', created_at timestamptz not null default now(), unique(company_id,name));
create table public.goals (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, parent_id uuid references public.goals, owner_agent_id uuid references public.agents, objective text not null, measures jsonb not null default '[]', status public.work_status not null default 'proposed', priority int not null default 50 check(priority between 0 and 100), deadline timestamptz, created_at timestamptz not null default now());
create table public.work_items (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, goal_id uuid references public.goals, owner_agent_id uuid references public.agents, objective text not null, proposal jsonb not null, status public.work_status not null default 'proposed', risk public.risk_level not null default 'low', idempotency_key text, progress numeric not null default 0 check(progress between 0 and 1), cost numeric not null default 0, next_run_at timestamptz, lease_until timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(company_id,idempotency_key));
create table public.events (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, type text not null, payload jsonb not null, causation_id uuid, correlation_id uuid, occurred_at timestamptz not null default now(), processed_at timestamptz);
create table public.memories (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, kind text not null check(kind in ('episodic','semantic','decision','procedural','relationship','agent')), subject text not null, content text not null, embedding vector(1536), importance real not null default .5 check(importance between 0 and 1), source_ids uuid[] not null default '{}', valid_from timestamptz, valid_to timestamptz, created_at timestamptz not null default now());
create table public.decisions (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, decided_by uuid references public.agents, question text not null, decision text not null, rationale text not null, alternatives jsonb not null default '[]', dissent jsonb not null default '[]', evidence jsonb not null default '[]', created_at timestamptz not null default now());
create table public.meetings (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, topic text not null, status text not null default 'live', context_snapshot jsonb not null, synthesis jsonb, started_at timestamptz not null default now(), ended_at timestamptz);
create table public.meeting_messages (id uuid primary key default gen_random_uuid(), meeting_id uuid not null references public.meetings on delete cascade, agent_id uuid references public.agents, content text not null, created_at timestamptz not null default now());
create table public.audit_log (id bigint generated always as identity primary key, company_id uuid not null references public.companies on delete cascade, actor_type text not null, actor_id text, action text not null, resource_type text not null, resource_id text, before_state jsonb, after_state jsonb, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.audit_findings (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, auditor_agent_id uuid references public.agents, severity public.risk_level not null, title text not null, evidence jsonb not null, recommendation text not null, status text not null default 'open', created_at timestamptz not null default now());
create table public.integration_connections (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, provider text not null, config jsonb not null default '{}', secret_reference text not null, enabled boolean not null default true, created_at timestamptz not null default now(), unique(company_id,provider));
create table public.integration_runs (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, connection_id uuid references public.integration_connections, operation text not null, idempotency_key text not null, request jsonb not null, response jsonb, status text not null default 'requested', approved_by uuid references auth.users, created_at timestamptz not null default now(), unique(company_id,idempotency_key));
create table public.metrics (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, key text not null, definition text not null, unit text not null, source text not null, created_at timestamptz not null default now(), unique(company_id,key));
create table public.metric_observations (metric_id uuid not null references public.metrics on delete cascade, observed_at timestamptz not null, value numeric not null, dimensions jsonb not null default '{}', provenance jsonb not null, primary key(metric_id,observed_at,dimensions));

create index memberships_user_idx on public.memberships(user_id,company_id); create index agents_company_idx on public.agents(company_id,status); create index goals_company_status_idx on public.goals(company_id,status); create index work_due_idx on public.work_items(company_id,next_run_at) where status in ('approved','running'); create index events_unprocessed_idx on public.events(company_id,occurred_at) where processed_at is null; create index memories_lookup_idx on public.memories(company_id,kind,importance desc); create index memories_embedding_idx on public.memories using hnsw (embedding vector_cosine_ops); create index audit_company_time_idx on public.audit_log(company_id,created_at desc); create index meeting_messages_meeting_idx on public.meeting_messages(meeting_id,created_at);

create function public.is_company_member(target_company uuid) returns boolean language sql stable security invoker set search_path='' as $$ select exists(select 1 from public.memberships m where m.company_id=target_company and m.user_id=(select auth.uid())) $$;
create function public.has_company_role(target_company uuid, allowed text[]) returns boolean language sql stable security invoker set search_path='' as $$ select exists(select 1 from public.memberships m where m.company_id=target_company and m.user_id=(select auth.uid()) and m.role=any(allowed)) $$;

alter table public.companies enable row level security; alter table public.memberships enable row level security; alter table public.departments enable row level security; alter table public.agents enable row level security; alter table public.goals enable row level security; alter table public.work_items enable row level security; alter table public.events enable row level security; alter table public.memories enable row level security; alter table public.decisions enable row level security; alter table public.meetings enable row level security; alter table public.meeting_messages enable row level security; alter table public.audit_log enable row level security; alter table public.audit_findings enable row level security; alter table public.integration_connections enable row level security; alter table public.integration_runs enable row level security; alter table public.metrics enable row level security; alter table public.metric_observations enable row level security;

create policy companies_read on public.companies for select to authenticated using(public.is_company_member(id));
create policy memberships_read on public.memberships for select to authenticated using(public.is_company_member(company_id));
create policy memberships_admin on public.memberships for all to authenticated using(public.has_company_role(company_id,array['owner'])) with check(public.has_company_role(company_id,array['owner']));
create policy departments_read on public.departments for select to authenticated using(public.is_company_member(company_id)); create policy departments_write on public.departments for all to authenticated using(public.has_company_role(company_id,array['owner','executive'])) with check(public.has_company_role(company_id,array['owner','executive']));
create policy agents_read on public.agents for select to authenticated using(public.is_company_member(company_id)); create policy agents_write on public.agents for all to authenticated using(public.has_company_role(company_id,array['owner','executive'])) with check(public.has_company_role(company_id,array['owner','executive']));
create policy goals_member on public.goals for select to authenticated using(public.is_company_member(company_id)); create policy goals_operator on public.goals for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy work_member on public.work_items for select to authenticated using(public.is_company_member(company_id)); create policy work_operator on public.work_items for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy events_member on public.events for select to authenticated using(public.is_company_member(company_id)); create policy events_operator on public.events for insert to authenticated with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy memories_member on public.memories for select to authenticated using(public.is_company_member(company_id)); create policy memories_operator on public.memories for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy decisions_member on public.decisions for select to authenticated using(public.is_company_member(company_id)); create policy decisions_exec on public.decisions for insert to authenticated with check(public.has_company_role(company_id,array['owner','executive']));
create policy meetings_member on public.meetings for select to authenticated using(public.is_company_member(company_id)); create policy meetings_exec on public.meetings for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy meeting_messages_member on public.meeting_messages for select to authenticated using(exists(select 1 from public.meetings m where m.id=meeting_id and public.is_company_member(m.company_id))); create policy meeting_messages_operator on public.meeting_messages for insert to authenticated with check(exists(select 1 from public.meetings m where m.id=meeting_id and public.has_company_role(m.company_id,array['owner','executive','operator'])));
create policy audit_read on public.audit_log for select to authenticated using(public.has_company_role(company_id,array['owner','auditor'])); create policy findings_read on public.audit_findings for select to authenticated using(public.is_company_member(company_id)); create policy findings_auditor on public.audit_findings for all to authenticated using(public.has_company_role(company_id,array['owner','auditor'])) with check(public.has_company_role(company_id,array['owner','auditor']));
create policy connections_admin on public.integration_connections for all to authenticated using(public.has_company_role(company_id,array['owner','executive'])) with check(public.has_company_role(company_id,array['owner','executive'])); create policy runs_read on public.integration_runs for select to authenticated using(public.is_company_member(company_id)); create policy runs_operator on public.integration_runs for insert to authenticated with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy metrics_member on public.metrics for select to authenticated using(public.is_company_member(company_id)); create policy metrics_operator on public.metrics for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator','auditor'])) with check(public.has_company_role(company_id,array['owner','executive','operator','auditor'])); create policy observations_member on public.metric_observations for select to authenticated using(exists(select 1 from public.metrics m where m.id=metric_id and public.is_company_member(m.company_id))); create policy observations_operator on public.metric_observations for insert to authenticated with check(exists(select 1 from public.metrics m where m.id=metric_id and public.has_company_role(m.company_id,array['owner','executive','operator','auditor'])));

revoke all on all tables in schema public from anon; grant select,insert,update,delete on all tables in schema public to authenticated; grant usage,select on all sequences in schema public to authenticated; revoke all on function public.is_company_member(uuid) from public; revoke all on function public.has_company_role(uuid,text[]) from public; grant execute on function public.is_company_member(uuid),public.has_company_role(uuid,text[]) to authenticated;
