create type public.website_presence as enum ('none','broken','social_only','platform_hosted','owned');
create type public.app_presence as enum ('none','published','unknown');
create type public.outreach_channel as enum ('email','phone','postal','contact_form','messaging');
create type public.outreach_outcome as enum ('queued','pending_approval','sent','bounced','replied','opted_out','blocked');

create table public.prospects (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, source text not null, source_ref text not null, fingerprint text not null, name text not null, category text not null default '', address jsonb not null default '{}', country_code char(2) not null, timezone text not null default 'UTC', declared_website text, social_profiles jsonb not null default '[]', attribution text, discovered_at timestamptz not null default now(), retain_until timestamptz, deleted_at timestamptz, unique(company_id,source,source_ref), unique(company_id,fingerprint));
create table public.prospect_contacts (id uuid primary key default gen_random_uuid(), prospect_id uuid not null references public.prospects on delete cascade, channel public.outreach_channel not null, value text not null, publicly_listed boolean not null default false, consent text not null default 'none' check(consent in ('none','opt_in')), source text not null, collected_at timestamptz not null default now(), unique(prospect_id,channel,value));
create table public.presence_assessments (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, prospect_id uuid not null references public.prospects on delete cascade, website public.website_presence not null, app public.app_presence not null default 'unknown', gap_score numeric not null check(gap_score between 0 and 1), confidence numeric not null check(confidence between 0 and 1), signals jsonb not null default '[]', assessed_at timestamptz not null default now());
create table public.demo_sites (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, prospect_id uuid not null references public.prospects on delete cascade, content jsonb not null, disclosure text not null, checksum text not null, preview_url text, takedown_token uuid not null default gen_random_uuid(), indexable boolean not null default false check(indexable = false), status text not null default 'published' check(status in ('draft','published','removed')), built_at timestamptz not null default now(), removed_at timestamptz, removal_reason text);
create table public.outreach_messages (id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies on delete cascade, prospect_id uuid not null references public.prospects on delete cascade, demo_site_id uuid references public.demo_sites on delete set null, channel public.outreach_channel not null, recipient text not null, touch int not null check(touch > 0), subject text not null, body text not null, sender_identity_block text not null, contact_source_disclosure text not null, opt_out_instruction text not null, compliance jsonb not null default '{}', status public.outreach_outcome not null default 'pending_approval', approval_id text, approved_by uuid references auth.users, composed_at timestamptz not null default now(), sent_at timestamptz, unique(company_id,prospect_id,touch));
create table public.outreach_suppression (company_id uuid not null references public.companies on delete cascade, value_hash text not null, reason text not null, created_at timestamptz not null default now(), primary key(company_id,value_hash));

create index prospects_company_idx on public.prospects(company_id,discovered_at desc) where deleted_at is null;
create index prospects_retention_idx on public.prospects(retain_until) where retain_until is not null and deleted_at is null;
create index presence_prospect_idx on public.presence_assessments(prospect_id,assessed_at desc);
create index demo_sites_prospect_idx on public.demo_sites(company_id,prospect_id,status);
create index outreach_messages_company_idx on public.outreach_messages(company_id,status,composed_at desc);
create index outreach_messages_daily_idx on public.outreach_messages(company_id,sent_at) where sent_at is not null;

alter table public.prospects enable row level security; alter table public.prospect_contacts enable row level security; alter table public.presence_assessments enable row level security; alter table public.demo_sites enable row level security; alter table public.outreach_messages enable row level security; alter table public.outreach_suppression enable row level security;

create policy prospects_member on public.prospects for select to authenticated using(public.is_company_member(company_id)); create policy prospects_operator on public.prospects for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy prospect_contacts_member on public.prospect_contacts for select to authenticated using(exists(select 1 from public.prospects p where p.id=prospect_id and public.is_company_member(p.company_id))); create policy prospect_contacts_operator on public.prospect_contacts for all to authenticated using(exists(select 1 from public.prospects p where p.id=prospect_id and public.has_company_role(p.company_id,array['owner','executive','operator']))) with check(exists(select 1 from public.prospects p where p.id=prospect_id and public.has_company_role(p.company_id,array['owner','executive','operator'])));
create policy presence_member on public.presence_assessments for select to authenticated using(public.is_company_member(company_id)); create policy presence_operator on public.presence_assessments for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy demo_sites_member on public.demo_sites for select to authenticated using(public.is_company_member(company_id)); create policy demo_sites_operator on public.demo_sites for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy outreach_member on public.outreach_messages for select to authenticated using(public.is_company_member(company_id)); create policy outreach_operator on public.outreach_messages for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator'])) with check(public.has_company_role(company_id,array['owner','executive','operator']));
create policy suppression_member on public.outreach_suppression for select to authenticated using(public.is_company_member(company_id)); create policy suppression_operator on public.outreach_suppression for all to authenticated using(public.has_company_role(company_id,array['owner','executive','operator','auditor'])) with check(public.has_company_role(company_id,array['owner','executive','operator','auditor']));

create function public.purge_expired_prospects() returns integer language sql security invoker set search_path='' as $$ with purged as (update public.prospects set deleted_at=now() where retain_until is not null and retain_until < now() and deleted_at is null returning 1) select count(*)::int from purged $$;
revoke all on function public.purge_expired_prospects() from public; grant execute on function public.purge_expired_prospects() to authenticated;
revoke all on public.prospects, public.prospect_contacts, public.presence_assessments, public.demo_sites, public.outreach_messages, public.outreach_suppression from anon;
grant select,insert,update,delete on public.prospects, public.prospect_contacts, public.presence_assessments, public.demo_sites, public.outreach_messages, public.outreach_suppression to authenticated;
